### ISSUE TITLE
[FEAT] Helper functions to provide token values instead of using tokens directly

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1650]
# :bulb: Feature request

## Feature Name

Provider helper functions

## The Desired Behavior

I want the API of providing a value for injection tokens (especially multi-tokens) to be abstracted into a provider function. Injection tokens often don't provide enough information to the user to indicate exactly how to provide values. Instead of exposing tokens directly, expose providers helper functions.

## Your Use Case

As an app dev, I want to be able to provide values for Daffodil token with functions, not directly.

## Prior Work

We accept driver configs in some `forRoot`s and also have some pure function provider helpers. I think all tokens meant for app dev use should have helper functions.

## Tasks

- [x] Create token/provider factories #2704
- [x] Migrate creation of tokens to use factory
  - [x] #3266
  - [x] #3232
  - [x] #3231
  - [x] #3230
  - [x] #3229
  - [x] #3228
  - [x] #3227
  - [x] #3226
  - [x] #3225
  - [x] #3224
  - [x] #3223
  - [x] #3222
  - [x] #3220
  - [x] #3219
  - [x] #3218
  - [x] #3217
  - [x] #3216
  - [x] #3215
  - [x] #3214
  - [x] #3213
  - [x] #3212
  - [x] #3211
  - [x] #3210
  - [x] #3209
  - [x] #3208
  - [x] #3207
  - [x] #3206
  - [x] #3205
  - [x] #3204
  - [x] #3203
  - [x] #3202
  - [x] #3201
- [ ] Migrate providing of tokens to use functions
  - [x] #3274
  - [x] #3279
  - [x] #3281
  - [x] #3284
  - [x] #3286
