### ISSUE TITLE
[FEAT] Allow out-of-the-box analytics tracking with external-router

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#2086]
# :bulb: Feature request

## Feature Name
Analaytics Trackable External Router

## The Desired Behavior

The `@daffodil/external-router` and the `@daffodil/seo` package work alongside the `@daffodil/analytics` package to set certain kinds of data (and track certain kinds of data). 

## Your Use Case
As a marketer, I would like to have some basic pageview tracking that works out of the box when using alongside `@daffodil/external-router`.

More generally, well-managed event-state coordination.

Currently, we face the following issues:

1. `@ngrx/router-store` Navigated occurs AFTER the page-history change event, which means analytics data is tracked at the wrong point in time.
2. We don't have any allowance for tracking Angular router events instead of ngrx events.
3. The data required to track analytics events correctly isn't quite available at the right point in time.

We can correct this with the following three features:

- [x] https://github.com/graycoreio/daffodil/pull/2083 Track events like RoutesRecognized, which contains RouterStateSnapshot which can contain additional data about a route. Importantly, RoutesRecognized is BEFORE the history change event which brings more "plug-and-play" friendly behavior to analytics. 
- [x] https://github.com/graycoreio/daffodil/pull/2084 Modifications to the `@daffodil/external-router` `daffInsertDataPathStrategy` to insert additional data onto a `daffPath`
- [x] https://github.com/graycoreio/daffodil/pull/2085 A v2.4.3 Magento external-router to return additional data that fulfills the title, meta_description, and canonical_url for the routes, giving just enough data to make analytics happy.

## Prior Work
Browser analytics trackers (like Google Analytics) have pre-baked conceptions of how pageviews work with the History Change API.  

## Environment

<pre><code>
Daffodil version: 0.41.0
Angular version: 13.3.1
