### ISSUE TITLE
Daffodil Packages Explorer

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#2682]
# :bulb: Feature request

## Feature Name
Daffodil Packages Explorer

### Phase 1 (Design)

- [x] Design the package explorer landing page (PELP) (mock up needed)
- [x] [The top nav will utilize the base nav of docs.daff.io where `Packages` is a primary link on the top nav.](https://github.com/graycoreio/daffodil/issues/2681)
- [x] A primary landing page that lists out all of the packages.
- [x] An individual package page will have a left sidebar that lists out all the packages so it's easy for developers to find another package.

### Phase 2 (Preparation)

- [x] #2694
- [x] #2696      
- [x] https://github.com/graycoreio/daffodil/issues/2685
- [x] #2693
- [x] #2695
- [x] #2813
- [x] #2815
- [x] #2816 
- [x] #2820
- [x] #2849
- [x] #2814

### Phase 2.5 (Per Package Preparation) 
- [ ] #3005 
- [ ] #2999
- [x] #2821
- [ ] #2975
- [x] #2971
- [ ] #2986 

### Phase 3 (Implementation)
- [x] Create the route and component for the PELP
- [x] #2818
- [x] #2819
- [x] Modify the docs generation for daff.io to include the package gen assets

### Phase 4 (nice to have)
- [x] #2851

## Your Use Case
As a Daffodil core developer, I want to be able to review specific documentation for each Daffodil package.

## Environment

<pre><code>
Daffodil version: 0.66.1
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
![image](https://github.com/graycoreio/daffodil/assets/9029654/966d22d8-20f1-46dd-9653-8bb58ce58a2b)
