### ISSUE TITLE
[DOCS] Docs describing the API, utilization and examples of the `@daffodil/design` package

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#2767]
# :page_facing_up: Documentation Request

## Docs Changes
- [x] Getting Started (#3271)
- [ ] Release Notes (#3303)
- [x] Tabs: Usage, API (#3123)
- [x] Colors
- [x] Typography
- [x] #1412
- [x] #2901 
- [ ] Add design tokens page and write documentation (#2801) 
- [ ] `@daffodil/design` SCSS Documentation 
    - [ ] SCSS API Reference ( #3405 )
    - [ ] SCSS Tutorials
         - [ ] #3393  
         - [x] Write a guide on how to make your custom component handle dark and light mode.
- [x] #2903 
- [x] #1235 

## Cleanup
 - [x] Deprecate and remove `daff-illuminate`. (#3772)

## Environment

<pre><code>
Daffodil version: X.Y.Z
Angular version: X.Y.Z 

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
There are only 3 large ideas remaining in order to mark this as closed.

- [ ] The example viewer's visibility in daff.io and the supporting infra around that #2903 
- [ ] An overarching review of the design component docs - #3771 
- [ ] SCSS Utilities documentation - #3405
