### ISSUE TITLE
[DOCS] Reorganize https://github.com/graycoreio/daffodil/tree/develop/docs

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#2822]
- [x] RELEASE.md - delete or move into docs/internal
  - [x] styles.md - move into docs/internal
  - [x] MAINTAINER.md - remove.
  - [x] INSTALLATION.md - remove.
  - [x] DEVELOPER.md - move to docs/internal
  - [x] CHANGELOG.md - move to root.
  - [x] state - move to internal (completed in #2829)
  - [x] architecture - keep and move to docs/guides/ (completed in #2829)
  - [ ] Write a "introduction.md" in docs/ (moved to #2835)
