### ISSUE TITLE
[FEAT] Newsletter Module

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#403]
# :bulb: Feature request

## Feature Name
`@daffodil/newsletter`

## TODO
- [x] New `@daffodil/newsletter` library
- [x] Ngrx state for library
  - [x] Reducers, Actions, Selectors, and Facades
- [x] Driver Interface Layer
- [x] Ngrx Effects
- [x] In-memory Backend
- [x] In-memory Driver
- [x] Testing Driver
- [x] Implementation in Demo
- [x] Implementation in daff.io
- [x] Magento 2 Driver
- [x] Shopify Driver
- [x] Guides

## The Desired Behavior
Installable newsletter module.

## Your Use Case
As a user, I would like to be able to subscribe to the newsletter of a store.

## Prior Work
N/A

**Comment by damienwebdev** [comment]
With the hubspot driver PR merged, I'm going to consider this initial issue completed.
